### ISSUE TITLE
aclocal-1.15 is missing

### ISSUE THREAD

**Issue by Enchufa2** [niceume/datasailr#2] opened 2020-10-04 15:03 UTC
Compilation of Onigmo fails on Fedora, see https://download.copr.fedorainfracloud.org/results/iucar/cran/fedora-32-x86_64/01694140-R-CRAN-datasailr/builder-live.log.gz

The buildroot contains aclocal-1.16. Why is it looking for 1.15 specifically?

**Comment by niceume** [comment] 2020-10-08 03:49
Thank you very much for reporting an issue.

First, DataSailr CRAN source package is packaged using https://github.com/niceume/datasailr_toolchain . What this toolchain does are to combine datasailr of this repository, libsailr and onigmo repositories, and to run some scripts beforehand to be accepted on CRAN. 

I run autoconf/autoreconf during datasailr_toolchain source packaging process, and rename autogen.sh into autogen.sh.done, by which CRAN build system does not need to run autoconf by themselves  (  https://github.com/niceume/datasailr_toolchain/blob/ed7e51669b9625048e89325174cbf9aa0f9868a7/create_datasailr_pkg.sh#L96-L121 and https://github.com/niceume/datasailr/blob/3b92c07e97a93aa2e85d26b4d177cd5c7306641d/configure.ac#L126-L131 ) I think the specification of 1.15 for aclocal comes from this process, and comes from my local machine where I run source package build toolchain. 

Aa far as I remember, I avoided CRAN systems' running autoconf because some of their  binary build systems do not have autoconf available (Sorry if I misunderstand). 

To fix this issue reported, the easiest way is to keep Onigmo's autogen.sh (not renamed). But this results in CRAN build systems' running autoconf, which might fail on autoconf unavailable systems. If I can have a mechanism within configure.ac (which is converted to configure when source package submission) to detect autoconf is available or not on binary build system OR to check aclocal version, this issue can be solved.

(Another solution can be to pass build option to when building binary package. --with-system-onigmo should work if Onigmo is available on the system.)

I do not have enough knowledge about autotools now. However, I think I need to cope with this issue, because in the future, some CRAN binary build systems may have such configurations.

**Comment by Enchufa2** [comment] 2020-10-08 08:39
It's quite strange, because if I download the sources to my Fedora desktop, it compiles just fine. The issue arises with automated buildsystems like this one I referenced. The thing is that the buildsystem unpackages the sources to perform some corrections if needed. My guess here is that, for some reason, the modification date of the files are changed a little bit so that the configure script thinks that files changed, and tries to re-run aclocal, etc., but a versioned aclocal, which is what fails.

Locally, for instance, I've been able to reproduce the issue in the following way:

```bash
tar xf datasailr_0.8.6.tar.gz && cd datasailr
git init && git add . && git commit -m "save state"
R_HOME=`R RHOME` ./configure # configures and compiles Onigmo just fine
git checkout . && git clean -fd # clean everything, remove created files
R_HOME=`R RHOME` ./configure # now it fails with aclocal-1.15: command not found
```

**Comment by niceume** [comment] 2020-10-15 02:10
I am sorry for late reply. Thank you for your investigation and reproducing the error in a simple way. 

As your code shows, the problem comes from how git deals with files. Git does not hold timestamps (as far as I know), but autotools depends on those information, which seems to cause unintentional aclocal re-running. I already run autoconf when I make this package, so aclocal should not run again.

If possible, I will try to find some way to work around this. (e.g. force stop running aclocal again or allow autoreconf again etc. )

**Comment by niceume** [comment] 2020-11-27 02:14
I think this problem is fixed in ver.0.8.7. Now users do not re-run autoconf even timestamps are lost.

AM_MAINTAINER_MODE([enable]) is added to Onigmo's configure.ac, which enables switching on/off maintainer-mode. 
( This modification for Onigmo is done in DataSailr packaging toolchain. https://github.com/niceume/datasailr/commit/9c9ee9ee02f595862cdbc9f53375cac8eb47fdb3 )

Then from DataSailr, ./configre is called with --disable-maintainer-mode option. ( https://github.com/niceume/datasailr_toolchain/commit/0e24b5a6ccc82dff35310c6b5ab65c0a28abe0f9 )

(ref) GNU automake manual: missing and AM_MAINTAINER_MODE https://www.gnu.org/software/automake/manual/html_node/maintainer_002dmode.html

**Closed** 2020-11-27 02:16 UTC
